# After edit do: cat k8s_secret_users.yml | openssl base64 -A
# And update the ambassador_users.yml with the result (without the last %)
# And apply: kubectl apply -f k8s_secret_users.yml
---
apiVersion: v1
kind: Secret
metadata:
  name: ambassador-auth-httpbasic-users
type: Opaque
data:
  users.yaml: "IyBqb2huZHVlOnBhc3N3b3JkCmpvaG5kdWU6CiAgaGFzaGVkX3Bhc3N3b3JkOiAiJDJiJDEyJGRiSXRiYkdweUtIcFMyTS40OG16aS5vUWdxVm82Q3JjTFBoNEpkSXZtVkw3NlBKcWJIdTdpIgo="
